const data = [{
        id: 1,
        title: 'Cat Gripes',
        text: 'Cat ipsum dolor sit amet, scamper. Eat grass, throw it back up spit up on light gray carpet instead of adjacent linoleum play riveting piece on synthesizer keyboard. Caticus cuteicus make meme, make cute face or destroy the blinds for chase red laser dot and Gate keepers of hell. Gate keepers of hell lick plastic bags wake up wander around the house making large amounts of noise jump on top of your human\'s bed and fall asleep again, claws in your leg or poop on grasses for soft kitty warm kitty little ball of furr. Plan steps for world domination sit by the fire. Leave dead animals as gifts the dog smells bad. Leave hair everywhere. Shove bum in owner\'s face like camera lens make muffins. Eat the fat cats food soft kitty warm kitty little ball of furr stare at ceiling light. Stare out the window refuse to drink water except out of someone\'s glass or find empty spot in cupboard and sleep all day and claw drapes. Lick the other cats eat owner\'s food eat a plant, kill a hand but climb a tree, wait for a fireman jump to fireman then scratch his face play time, so chew foot. Plan steps for world domination chirp at birds sit in box or sit by the fire inspect anything brought into the house. Chirp at birds refuse to leave cardboard box chase red laser dot you call this cat food? yet spread kitty litter all over house. Who\'s the baby knock dish off table head butt cant eat out of my own dish. Meow for food, then when human fills food dish, take a few bites of food and continue meowing leave hair everywhere hunt anything that moves, but curl into a furry donut play riveting piece on synthesizer keyboard. Roll on the floor purring your whiskers off sit on human shove bum in owner\'s face like camera lens but scamper has closed eyes but still sees you scream at teh bath for leave hair everywhere. Destroy couch spread kitty litter all over house eat from dog\'s food spot something, big eyes, big eyes, crouch, shake butt, prepare to pounce but soft kitty warm kitty little ball of furr for sit on human. Cough furball inspect anything brought into the house. Curl into a furry donut under the bed, for fall asleep on the washing machine refuse to leave cardboard box. Sweet beast lick butt and make a weird face. Lick plastic bags if it smells like fish eat as much as you wish present belly, scratch hand when stroked but sleep on dog bed, force dog to sleep on floor yet meow all night having their mate disturbing sleeping humans eat from dog\'s food put toy mouse in food bowl run out of litter box at full speed . Scream at teh bath always hungry but kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff climb leg, for meow for food, then when human fills food dish, take a few bites of food and continue meowing.'
    },

    {
        id: 2,
        title: 'Cat Life',
        text: 'Stare at wall turn and meow stare at wall some more meow again continue staring eat prawns daintily with a claw then lick paws clean wash down prawns with a lap of carnation milk then retire to the warmest spot on the couch to claw at the fabric before taking a catnap and chase mice. Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff inspect anything brought into the house, yet hate dog, yet i am the best and see owner, run in terror. Attack dog, run away and pretend to be victim. This human feeds me, i should be a god stares at human while pushing stuff off a table and hiss at vacuum cleaner. Kitty power! eat and than sleep on your face brown cats with pink ears but hate dog, so hide head under blanket so no one can see chew on cable so i am the best. '
    },
    {
      id: 3,
      title: 'Cat Love',
      text: 'Cat is love, cat is life. Scratch the furniture run outside as soon as door open but intently stare at the same spot, yet wake up wander around the house making large amounts of noise jump on top of your human\'s bed and fall asleep again. Destroy couch lick the plastic bag. Get video posted to internet for chasing red dot roll on the floor purring your whiskers off unwrap toilet paper, sleep in the bathroom sink curl into a furry donut. Cat is love, cat is life. Pelt around the house and up and down stairs chasing phantoms find empty spot in cupboard and sleep all day, wake up human for food at 4am, claws in your leg but chew on cable. Missing until dinner time missing until dinner time chase laser so sleep nap, sniff other cat\'s butt and hang jaw half open thereafter or pee in the shoe massacre a bird in the living room and then look like the cutest and most innocent animal on the planet. Bathe private parts with tongue then lick owner\'s face scratch leg; meow for can opener to feed me and knock dish off table head butt cant eat out of my own dish and lick arm hair, toy mouse squeak roll over or all of a sudden cat goes crazy. Scream at teh bath refuse to leave cardboard box use lap as chair lick butt and make a weird face and all of a sudden cat goes crazy. Knock over christmas tree nap all day use lap as chair attack feet, and curl into a furry donut or white cat sleeps on a black shirt and roll on the floor purring your whiskers off. Fall asleep on the washing machine vommit food and eat it again pooping rainbow while flying in a toasted bread costume in space but bathe private parts with tongue then lick owner\'s face but paw at your fat belly lick butt. Roll on the floor purring your whiskers off climb a tree, wait for a fireman jump to fireman then scratch his face.'
    }
]

export default data;
